apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sportsdev-basic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kundan547/spring-boot-k8s-2.git
    targetRevision: HEAD
    path: kds
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      