name: CI/CD to Docker Hub

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build Spring Boot app with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/spring-boot-k8s-2
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/spring-boot-k8s-2
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
